name: senior_active_adventure
description: Action Based Fitness Game for Elderly

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.17.0
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.10.1
  google_sign_in: ^6.1.5

  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.4
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_secure_storage: ^9.0.0
  auto_route: ^8.0.3
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  path_provider: ^2.1.2
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.67.0
  percent_indicator: ^4.2.3
  auto_size_text: ^3.0.0
  flex_color_scheme: ^7.3.1
  convex_bottom_bar: ^3.2.0
  flutter_gemini: ^2.0.3
  google_generative_ai: ^0.3.1
  animated_text_kit: ^4.2.2
  flutter_markdown: ^0.7.1
  google_fonts: ^6.2.1
  markdown: ^7.2.2
  url_launcher: ^6.2.6
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  auto_route_generator: ^8.0.0
  change_app_package_name: ^1.1.0

# dependency_overrides:
#   analyzer: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ui/
    - assets/monsters/